#put all config here
USER_DB_NAME: user_db
USER_DB_USER: postgres
USER_DB_PASSWORD: 123
USER_DB_HOST: localhost
USER_DB_PORT: 5432

TRACK_AND_TRACE_DB_NAME: track_and_trace
TRACK_AND_TRACE_DB_USER: postgres
TRACK_AND_TRACE_DB_PASSWORD: 123
TRACK_AND_TRACE_DB_HOST: localhost
TRACK_AND_TRACE_DB_PORT: 5432
